name: First action that post a welcome comment
on:
  pull_request:
    types: [opened]
  permissions:
    pull-requests: write
  jobs:
    welcome:
      name: My first job named welcome
      runs-on: ubuntu-latest
  
